Dev mpatch 1
airex-lab/CAESAR pull request #26
Opened 2024-07-24 06:57 UTC by DebajyotiSahoo13

2024-07-24 12:09 UTC, lokeshmohanty requested changes
Good work! Make the suggested changes.

You will have to add tests cases for all these as currently it is not obvious if there are any problems with the code, though that can be done in a separate pull request after this is merged.

2024-07-24 12:09 UTC, lokeshmohanty commented on src/model/plots/agglomerative_clustering_3d.png
Plots should not be tracked by git

2024-07-24 12:09 UTC, lokeshmohanty commented on src/data/data_loader.py
> +    @staticmethod
Any reason for making these methods static?

2024-07-24 12:09 UTC, lokeshmohanty commented on src/data/data_loader.py
The file name is too generic, you can change it something like `radar-synthetic.py`

2024-07-24 12:10 UTC, lokeshmohanty commented
Change the commit messages as well. The current one's are not very helpful. You can merge all changes into a single commit with message "add common clustering algorithms" with proper description.

2024-07-25 03:02 UTC, lokeshmohanty commented
You can install matplotlib by using `poetry add matplotlib`. That will add it to poetry.lock file and pyproject.toml

2024-07-25 05:45 UTC, DebajyotiSahoo13 commented
@lokeshmohanty  Cleared all test checks.Please review and suggest changes.
I will rebase all the git commit messages at the very end.
Let me know if any change in code structure.

2024-07-25 06:24 UTC, lokeshmohanty reviewed
- `.dvc` directory has lot of duplicate files. Remove all the duplicates.
- If you intend to rename `data` folder to `dataset`, don't just duplicate it and name it `dataset`, you need to remove the `data` folder as well.

2024-07-25 06:24 UTC, lokeshmohanty commented on src/data/data_loader.py
You duplicated this file. Delete it.

2024-07-25 06:24 UTC, lokeshmohanty commented on src/main.py
> +# import os
Remove these comments

2024-07-25 06:24 UTC, lokeshmohanty commented on .gitignore
> +/src/plots/
Don't add `/src/plots` in gitignore. All the files to be ignored should be put outside `src` folder

2024-07-25 07:11 UTC, DebajyotiSahoo13 commented
@lokeshmohanty Made the changes, do let me know if any other changes

2024-07-26 05:18 UTC, closed without merging